# Base configs
baseurl: ""
url: "http://opsbug.com/arcosanti"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Vikram Dhillon"
subtitle: "Always forward"
author: "Vikram Dhillon"
bio: "Developer, student and now learning photography"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/opsbug"
  